---
app_user                             : sso_auth_service
app_group                            : sso_auth_service
app_log_tag_name                     : '{{ app_name }}'
config_file                          : '/auth_service/config/development/application.yml'
server_name                          : localhost
db_url                               : jdbc:postgresql://localhost:5432/auth_service_dev
db_user                              : postgres
db_pass                              :
db_host                              : localhost
db_name                              : auth_service_dev
environment_name                     : dev

#kafka & Zookeeper

kafka_version                        : 2.7.0

zookeeper_group                      : zookeeper
zookeeper_user                       : zookeeper
zookeeper_hosts                      : localhost
zookeeper_client_port                : 2181
zookeeper_conf_dir                   : /etc/zookeeper/conf
zookeeper_log_dir                    : /var/log/zookeeper
zookeeper_data_dir                   : /var/lib/zookeeper
zookeeper_systemd_service            : /etc/systemd/system/zookeeper.service
zookeeper_maxClientCnxns             : 60
zookeeper_id                         : 1
zookeeper_jmx_disable                : true
zookeeper_jvm_flags                  :
zookeeper_opts                       :
zookeeper_heap_opts                  : '-Xms64m -Xmx64m'
zookeeper_jmx_opts                   :

zookeeper_connection_timeout_ms      : 6000
zookeeper_set_acl                    : false

kafka_group                          : kafka
kafka_user                           : kafka
kafka_home                           : /home/{{kafka_user}}
kafka_broker_id                      : 0
kafka_download_url                   : 'https://archive.apache.org/dist/kafka/{{kafka_version}}/kafka_2.12-{{kafka_version}}.tgz'
kafka_binary_archive                 : /opt/kafka_2.12-{{kafka_version}}.tgz
kafka_binary_dir                     : /opt/kafka_2.12-{{kafka_version}}
kafka_listen_address                 : "localhost"

kafka_conf_dir                       : /etc/kafka
kafka_data_dir                       : /app/kafka/data
kafka_log_dir                        : /var/log/kafka
kafka_upstart_conf                   : /etc/init/kafka.conf
kafka_systemd_service                : /etc/systemd/system/kafka.service
kafka_auto_create_topics             : true
kafka_delete_topic                   : true
kafka_broker_id_generation_enable    : true
replication_factor                   : 1
partition                            : 1
transaction_log_replication_factor   : 1
transaction_log_min_isr              : 1
kafka_host_name                      : "{{ansible_hostname}}"
kafka_advertised_listeners           : "PLAINTEXT://{{ansible_default_ipv4.address}}:9092"
kafka_advertised_host_name           : "{{ansible_hostname}}"
kafka_advertised_port                : 9092

kafka_zookeeper_hosts                : 'localhost:2181'
kafka_num_network_threads            : 3
kafka_num_io_threads                 : 8
kafka_num_partitions                 : 1
kafka_socket_send_buffer_bytes       : 102400
kafka_socket_receive_buffer_bytes    : 102400
kafka_socket_request_max_bytes       : 104857600
kafka_log_flush_interval_messages    : 9223372036854775807
kafka_log_flush_interval_ms          : 1000
kafka_log_retention_bytes            : -1
kafka_log_retention_hours            : 24
kafka_log_retention_check_interval_ms: 60000
kafka_log_segment_bytes              : 1073741824
log_cleanup_policy                   : compact
kafka_opts                           :
kafka_heap_opts                      : '-Xms256m -Xmx256m'
kafka_jmx_opts                       :
log_cleanup_ratio                    : 0.5

kafka_listeners                      : 'PLAINTEXT://{{kafka_listen_address}}:9092'

kafka_security_inter_broker_protocol : PLAINTEXT

verify                               : true

topics                               :
  - topic: "auth_user_sync_topic"
