---
- name   : NGINX | Add signing key
  apt_key:
    url  : http://nginx.org/keys/nginx_signing.key
    state: present

- name      : NGINX | Update source files list with deb url
  lineinfile:
    dest: /etc/apt/sources.list
    line: "deb https://nginx.org/packages/mainline/ubuntu/ focal nginx"

- name      : NGINX | Update source files list with deb-src url
  lineinfile:
    dest: /etc/apt/sources.list
    line: "deb-src https://nginx.org/packages/mainline/ubuntu/ focal nginx"

- name: NGINX | Install
  apt :
    name        : nginx
    state       : latest
    update_cache: True

- name    : NGINX | Update configuration file with template
  template:
    src : files/nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0755

- name   : NGINX | enable and restart the service
  systemd:
    name   : nginx
    state  : restarted
    enabled: True
